### ISSUE TITLE
Totally Awesome!

### ISSUE THREAD

**Issue by sirvon** [Nublo/HallScheme#15]
Hey, what made you come up with this lib?
This is absolutely freaking brilliant.

With diverse use case!

thank you for your time!

**Comment by Nublo** [comment]
Sirvon, Thank you!
It is great to read this kind of feedback. And also the best motivation to continue library development.

Idea of library comes to me when i was working on project where you can buy tickets on different events. And when i tried to find any open source library for this i found nothing. So later i decided to create library for future developers.

**Comment by sirvon** [comment]
This will definitely come in super handy going forward for any mass/audience based "situational" app.
Which describes a LARGE portion of occurrances in every major city. From public transportation seating to class room environments.

We need this in react-native so it can be used for ios AND android.

thank you again!
